-- Run this SQL in your Supabase SQL Editor (https://supabase.com/dashboard/project/osjjxyqyifgpwfvlxczc/sql/new)

CREATE TABLE IF NOT EXISTS public.marketplace_postings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Local Sales',
  type TEXT DEFAULT 'sale',
  price NUMERIC DEFAULT 0,
  description TEXT DEFAULT '',
  image_url TEXT DEFAULT '',
  contact_phone TEXT DEFAULT '',
  location_name TEXT DEFAULT 'Calicut',
  lat DOUBLE PRECISION DEFAULT 11.1495,
  lng DOUBLE PRECISION DEFAULT 75.9723,
  customer_id UUID,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS & set public permissions so Customer App and Admin Panel can sync seamlessly
ALTER TABLE public.marketplace_postings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access on marketplace_postings" ON public.marketplace_postings;
CREATE POLICY "Allow public read access on marketplace_postings"
  ON public.marketplace_postings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert access on marketplace_postings" ON public.marketplace_postings;
CREATE POLICY "Allow public insert access on marketplace_postings"
  ON public.marketplace_postings FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update access on marketplace_postings" ON public.marketplace_postings;
CREATE POLICY "Allow public update access on marketplace_postings"
  ON public.marketplace_postings FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete access on marketplace_postings" ON public.marketplace_postings;
CREATE POLICY "Allow public delete access on marketplace_postings"
  ON public.marketplace_postings FOR DELETE USING (true);
